/* Bilingual ISO 3166-1 alpha-2 country list — 249 entries.
   Generated from Intl.DisplayNames (CLDR). Format: [code, English, Arabic].
   Sorted at runtime by the active language via Intl.Collator; see js/app.js. */
window.COUNTRIES = [
  ["AD", "Andorra", "أندورا"],
  ["AE", "United Arab Emirates", "الإمارات العربية المتحدة"],
  ["AF", "Afghanistan", "أفغانستان"],
  ["AG", "Antigua & Barbuda", "أنتيغوا وبربودا"],
  ["AI", "Anguilla", "أنغويلا"],
  ["AL", "Albania", "ألبانيا"],
  ["AM", "Armenia", "أرمينيا"],
  ["AO", "Angola", "أنغولا"],
  ["AQ", "Antarctica", "أنتاركتيكا"],
  ["AR", "Argentina", "الأرجنتين"],
  ["AS", "American Samoa", "ساموا الأمريكية"],
  ["AT", "Austria", "النمسا"],
  ["AU", "Australia", "أستراليا"],
  ["AW", "Aruba", "أروبا"],
  ["AX", "Åland Islands", "جزر آلاند"],
  ["AZ", "Azerbaijan", "أذربيجان"],
  ["BA", "Bosnia & Herzegovina", "البوسنة والهرسك"],
  ["BB", "Barbados", "بربادوس"],
  ["BD", "Bangladesh", "بنغلاديش"],
  ["BE", "Belgium", "بلجيكا"],
  ["BF", "Burkina Faso", "بوركينا فاسو"],
  ["BG", "Bulgaria", "بلغاريا"],
  ["BH", "Bahrain", "البحرين"],
  ["BI", "Burundi", "بوروندي"],
  ["BJ", "Benin", "بنين"],
  ["BL", "St. Barthélemy", "سان بارتليمي"],
  ["BM", "Bermuda", "برمودا"],
  ["BN", "Brunei", "بروناي"],
  ["BO", "Bolivia", "بوليفيا"],
  ["BQ", "Caribbean Netherlands", "هولندا الكاريبية"],
  ["BR", "Brazil", "البرازيل"],
  ["BS", "Bahamas", "جزر البهاما"],
  ["BT", "Bhutan", "بوتان"],
  ["BV", "Bouvet Island", "جزيرة بوفيه"],
  ["BW", "Botswana", "بوتسوانا"],
  ["BY", "Belarus", "بيلاروس"],
  ["BZ", "Belize", "بليز"],
  ["CA", "Canada", "كندا"],
  ["CC", "Cocos (Keeling) Islands", "جزر كوكوس (كيلينغ)"],
  ["CD", "Congo - Kinshasa", "الكونغو - كينشاسا"],
  ["CF", "Central African Republic", "جمهورية أفريقيا الوسطى"],
  ["CG", "Congo - Brazzaville", "الكونغو - برازافيل"],
  ["CH", "Switzerland", "سويسرا"],
  ["CI", "Côte d’Ivoire", "ساحل العاج"],
  ["CK", "Cook Islands", "جزر كوك"],
  ["CL", "Chile", "تشيلي"],
  ["CM", "Cameroon", "الكاميرون"],
  ["CN", "China", "الصين"],
  ["CO", "Colombia", "كولومبيا"],
  ["CR", "Costa Rica", "كوستاريكا"],
  ["CU", "Cuba", "كوبا"],
  ["CV", "Cape Verde", "الرأس الأخضر"],
  ["CW", "Curaçao", "كوراساو"],
  ["CX", "Christmas Island", "جزيرة كريسماس"],
  ["CY", "Cyprus", "قبرص"],
  ["CZ", "Czechia", "التشيك"],
  ["DE", "Germany", "ألمانيا"],
  ["DJ", "Djibouti", "جيبوتي"],
  ["DK", "Denmark", "الدانمرك"],
  ["DM", "Dominica", "دومينيكا"],
  ["DO", "Dominican Republic", "جمهورية الدومينيكان"],
  ["DZ", "Algeria", "الجزائر"],
  ["EC", "Ecuador", "الإكوادور"],
  ["EE", "Estonia", "إستونيا"],
  ["EG", "Egypt", "مصر"],
  ["EH", "Western Sahara", "الصحراء الغربية"],
  ["ER", "Eritrea", "إريتريا"],
  ["ES", "Spain", "إسبانيا"],
  ["ET", "Ethiopia", "إثيوبيا"],
  ["FI", "Finland", "فنلندا"],
  ["FJ", "Fiji", "فيجي"],
  ["FK", "Falkland Islands", "جزر فوكلاند"],
  ["FM", "Micronesia", "ميكرونيزيا"],
  ["FO", "Faroe Islands", "جزر فارو"],
  ["FR", "France", "فرنسا"],
  ["GA", "Gabon", "الغابون"],
  ["GB", "United Kingdom", "المملكة المتحدة"],
  ["GD", "Grenada", "غرينادا"],
  ["GE", "Georgia", "جورجيا"],
  ["GF", "French Guiana", "غويانا الفرنسية"],
  ["GG", "Guernsey", "غيرنزي"],
  ["GH", "Ghana", "غانا"],
  ["GI", "Gibraltar", "جبل طارق"],
  ["GL", "Greenland", "غرينلاند"],
  ["GM", "Gambia", "غامبيا"],
  ["GN", "Guinea", "غينيا"],
  ["GP", "Guadeloupe", "غوادلوب"],
  ["GQ", "Equatorial Guinea", "غينيا الاستوائية"],
  ["GR", "Greece", "اليونان"],
  ["GS", "South Georgia & South Sandwich Islands", "جورجيا الجنوبية وجزر ساندويتش الجنوبية"],
  ["GT", "Guatemala", "غواتيمالا"],
  ["GU", "Guam", "غوام"],
  ["GW", "Guinea-Bissau", "غينيا بيساو"],
  ["GY", "Guyana", "غيانا"],
  ["HK", "Hong Kong SAR China", "هونغ كونغ الصينية (منطقة إدارية خاصة)"],
  ["HM", "Heard & McDonald Islands", "جزيرة هيرد وجزر ماكدونالد"],
  ["HN", "Honduras", "هندوراس"],
  ["HR", "Croatia", "كرواتيا"],
  ["HT", "Haiti", "هايتي"],
  ["HU", "Hungary", "هنغاريا"],
  ["ID", "Indonesia", "إندونيسيا"],
  ["IE", "Ireland", "أيرلندا"],
  ["IL", "Israel", "إسرائيل"],
  ["IM", "Isle of Man", "جزيرة مان"],
  ["IN", "India", "الهند"],
  ["IO", "British Indian Ocean Territory", "الإقليم البريطاني في المحيط الهندي"],
  ["IQ", "Iraq", "العراق"],
  ["IR", "Iran", "إيران"],
  ["IS", "Iceland", "آيسلندا"],
  ["IT", "Italy", "إيطاليا"],
  ["JE", "Jersey", "جيرسي"],
  ["JM", "Jamaica", "جامايكا"],
  ["JO", "Jordan", "الأردن"],
  ["JP", "Japan", "اليابان"],
  ["KE", "Kenya", "كينيا"],
  ["KG", "Kyrgyzstan", "قيرغيزستان"],
  ["KH", "Cambodia", "كمبوديا"],
  ["KI", "Kiribati", "كيريباتي"],
  ["KM", "Comoros", "جزر القمر"],
  ["KN", "St. Kitts & Nevis", "سانت كيتس ونيفيس"],
  ["KP", "North Korea", "كوريا الشمالية"],
  ["KR", "South Korea", "كوريا الجنوبية"],
  ["KW", "Kuwait", "الكويت"],
  ["KY", "Cayman Islands", "جزر كايمان"],
  ["KZ", "Kazakhstan", "كازاخستان"],
  ["LA", "Laos", "لاوس"],
  ["LB", "Lebanon", "لبنان"],
  ["LC", "St. Lucia", "سانت لوسيا"],
  ["LI", "Liechtenstein", "ليختنشتاين"],
  ["LK", "Sri Lanka", "سريلانكا"],
  ["LR", "Liberia", "ليبيريا"],
  ["LS", "Lesotho", "ليسوتو"],
  ["LT", "Lithuania", "ليتوانيا"],
  ["LU", "Luxembourg", "لوكسمبورغ"],
  ["LV", "Latvia", "لاتفيا"],
  ["LY", "Libya", "ليبيا"],
  ["MA", "Morocco", "المغرب"],
  ["MC", "Monaco", "موناكو"],
  ["MD", "Moldova", "مولدوفا"],
  ["ME", "Montenegro", "الجبل الأسود"],
  ["MF", "St. Martin", "سان مارتن"],
  ["MG", "Madagascar", "مدغشقر"],
  ["MH", "Marshall Islands", "جزر مارشال"],
  ["MK", "North Macedonia", "مقدونيا الشمالية"],
  ["ML", "Mali", "مالي"],
  ["MM", "Myanmar (Burma)", "ميانمار (بورما)"],
  ["MN", "Mongolia", "منغوليا"],
  ["MO", "Macao SAR China", "منطقة ماكاو الإدارية الخاصة"],
  ["MP", "Northern Mariana Islands", "جزر ماريانا الشمالية"],
  ["MQ", "Martinique", "جزر المارتينيك"],
  ["MR", "Mauritania", "موريتانيا"],
  ["MS", "Montserrat", "مونتسرات"],
  ["MT", "Malta", "مالطا"],
  ["MU", "Mauritius", "موريشيوس"],
  ["MV", "Maldives", "جزر المالديف"],
  ["MW", "Malawi", "ملاوي"],
  ["MX", "Mexico", "المكسيك"],
  ["MY", "Malaysia", "ماليزيا"],
  ["MZ", "Mozambique", "موزمبيق"],
  ["NA", "Namibia", "ناميبيا"],
  ["NC", "New Caledonia", "كاليدونيا الجديدة"],
  ["NE", "Niger", "النيجر"],
  ["NF", "Norfolk Island", "جزيرة نورفولك"],
  ["NG", "Nigeria", "نيجيريا"],
  ["NI", "Nicaragua", "نيكاراغوا"],
  ["NL", "Netherlands", "هولندا"],
  ["NO", "Norway", "النرويج"],
  ["NP", "Nepal", "نيبال"],
  ["NR", "Nauru", "ناورو"],
  ["NU", "Niue", "نيوي"],
  ["NZ", "New Zealand", "نيوزيلندا"],
  ["OM", "Oman", "عُمان"],
  ["PA", "Panama", "بنما"],
  ["PE", "Peru", "بيرو"],
  ["PF", "French Polynesia", "بولينيزيا الفرنسية"],
  ["PG", "Papua New Guinea", "بابوا غينيا الجديدة"],
  ["PH", "Philippines", "الفلبين"],
  ["PK", "Pakistan", "باكستان"],
  ["PL", "Poland", "بولندا"],
  ["PM", "St. Pierre & Miquelon", "سان بيير ومكويلون"],
  ["PN", "Pitcairn Islands", "جزر بيتكيرن"],
  ["PR", "Puerto Rico", "بورتوريكو"],
  ["PS", "Palestinian Territories", "الأراضي الفلسطينية"],
  ["PT", "Portugal", "البرتغال"],
  ["PW", "Palau", "بالاو"],
  ["PY", "Paraguay", "باراغواي"],
  ["QA", "Qatar", "قطر"],
  ["RE", "Réunion", "روينيون"],
  ["RO", "Romania", "رومانيا"],
  ["RS", "Serbia", "صربيا"],
  ["RU", "Russia", "روسيا"],
  ["RW", "Rwanda", "رواندا"],
  ["SA", "Saudi Arabia", "المملكة العربية السعودية"],
  ["SB", "Solomon Islands", "جزر سليمان"],
  ["SC", "Seychelles", "سيشل"],
  ["SD", "Sudan", "السودان"],
  ["SE", "Sweden", "السويد"],
  ["SG", "Singapore", "سنغافورة"],
  ["SH", "St. Helena", "سانت هيلينا"],
  ["SI", "Slovenia", "سلوفينيا"],
  ["SJ", "Svalbard & Jan Mayen", "سفالبارد وجان ماين"],
  ["SK", "Slovakia", "سلوفاكيا"],
  ["SL", "Sierra Leone", "سيراليون"],
  ["SM", "San Marino", "سان مارينو"],
  ["SN", "Senegal", "السنغال"],
  ["SO", "Somalia", "الصومال"],
  ["SR", "Suriname", "سورينام"],
  ["SS", "South Sudan", "جنوب السودان"],
  ["ST", "São Tomé & Príncipe", "ساو تومي وبرينسيبي"],
  ["SV", "El Salvador", "السلفادور"],
  ["SX", "Sint Maarten", "سانت مارتن"],
  ["SY", "Syria", "سوريا"],
  ["SZ", "Eswatini", "إسواتيني"],
  ["TC", "Turks & Caicos Islands", "جزر توركس وكايكوس"],
  ["TD", "Chad", "تشاد"],
  ["TF", "French Southern Territories", "الأقاليم الجنوبية الفرنسية"],
  ["TG", "Togo", "توغو"],
  ["TH", "Thailand", "تايلاند"],
  ["TJ", "Tajikistan", "طاجيكستان"],
  ["TK", "Tokelau", "توكيلاو"],
  ["TL", "Timor-Leste", "تيمور - ليشتي"],
  ["TM", "Turkmenistan", "تركمانستان"],
  ["TN", "Tunisia", "تونس"],
  ["TO", "Tonga", "تونغا"],
  ["TR", "Türkiye", "تركيا"],
  ["TT", "Trinidad & Tobago", "ترينيداد وتوباغو"],
  ["TV", "Tuvalu", "توفالو"],
  ["TW", "Taiwan", "تايوان"],
  ["TZ", "Tanzania", "تنزانيا"],
  ["UA", "Ukraine", "أوكرانيا"],
  ["UG", "Uganda", "أوغندا"],
  ["UM", "U.S. Outlying Islands", "جزر الولايات المتحدة النائية"],
  ["US", "United States", "الولايات المتحدة"],
  ["UY", "Uruguay", "أورغواي"],
  ["UZ", "Uzbekistan", "أوزبكستان"],
  ["VA", "Vatican City", "الفاتيكان"],
  ["VC", "St. Vincent & Grenadines", "سانت فنسنت وجزر غرينادين"],
  ["VE", "Venezuela", "فنزويلا"],
  ["VG", "British Virgin Islands", "جزر فيرجن البريطانية"],
  ["VI", "U.S. Virgin Islands", "جزر فيرجن الأمريكية"],
  ["VN", "Vietnam", "فيتنام"],
  ["VU", "Vanuatu", "فانواتو"],
  ["WF", "Wallis & Futuna", "جزر والس وفوتونا"],
  ["WS", "Samoa", "ساموا"],
  ["YE", "Yemen", "اليمن"],
  ["YT", "Mayotte", "مايوت"],
  ["ZA", "South Africa", "جنوب أفريقيا"],
  ["ZM", "Zambia", "زامبيا"],
  ["ZW", "Zimbabwe", "زيمبابوي"]
];

/* ITU-T E.164 country calling codes, keyed by the same ISO 3166-1 alpha-2
   codes as COUNTRIES above — one entry for all 249, so the dialling select
   and the nationality select can never fall out of step.

   Territories sharing a code with their administering state carry that code
   (Åland +358, Svalbard +47, Western Sahara +212), and the NANP members all
   carry a bare +1; the area code that distinguishes them belongs to the
   national number the client types, not to the country code. */
window.DIAL_CODES = {
  AD: '376',  AE: '971',  AF: '93',   AG: '1',    AI: '1',    AL: '355',
  AM: '374',  AO: '244',  AQ: '672',  AR: '54',   AS: '1',    AT: '43',
  AU: '61',   AW: '297',  AX: '358',  AZ: '994',  BA: '387',  BB: '1',
  BD: '880',  BE: '32',   BF: '226',  BG: '359',  BH: '973',  BI: '257',
  BJ: '229',  BL: '590',  BM: '1',    BN: '673',  BO: '591',  BQ: '599',
  BR: '55',   BS: '1',    BT: '975',  BV: '47',   BW: '267',  BY: '375',
  BZ: '501',  CA: '1',    CC: '61',   CD: '243',  CF: '236',  CG: '242',
  CH: '41',   CI: '225',  CK: '682',  CL: '56',   CM: '237',  CN: '86',
  CO: '57',   CR: '506',  CU: '53',   CV: '238',  CW: '599',  CX: '61',
  CY: '357',  CZ: '420',  DE: '49',   DJ: '253',  DK: '45',   DM: '1',
  DO: '1',    DZ: '213',  EC: '593',  EE: '372',  EG: '20',   EH: '212',
  ER: '291',  ES: '34',   ET: '251',  FI: '358',  FJ: '679',  FK: '500',
  FM: '691',  FO: '298',  FR: '33',   GA: '241',  GB: '44',   GD: '1',
  GE: '995',  GF: '594',  GG: '44',   GH: '233',  GI: '350',  GL: '299',
  GM: '220',  GN: '224',  GP: '590',  GQ: '240',  GR: '30',   GS: '500',
  GT: '502',  GU: '1',    GW: '245',  GY: '592',  HK: '852',  HM: '672',
  HN: '504',  HR: '385',  HT: '509',  HU: '36',   ID: '62',   IE: '353',
  IL: '972',  IM: '44',   IN: '91',   IO: '246',  IQ: '964',  IR: '98',
  IS: '354',  IT: '39',   JE: '44',   JM: '1',    JO: '962',  JP: '81',
  KE: '254',  KG: '996',  KH: '855',  KI: '686',  KM: '269',  KN: '1',
  KP: '850',  KR: '82',   KW: '965',  KY: '1',    KZ: '7',    LA: '856',
  LB: '961',  LC: '1',    LI: '423',  LK: '94',   LR: '231',  LS: '266',
  LT: '370',  LU: '352',  LV: '371',  LY: '218',  MA: '212',  MC: '377',
  MD: '373',  ME: '382',  MF: '590',  MG: '261',  MH: '692',  MK: '389',
  ML: '223',  MM: '95',   MN: '976',  MO: '853',  MP: '1',    MQ: '596',
  MR: '222',  MS: '1',    MT: '356',  MU: '230',  MV: '960',  MW: '265',
  MX: '52',   MY: '60',   MZ: '258',  NA: '264',  NC: '687',  NE: '227',
  NF: '672',  NG: '234',  NI: '505',  NL: '31',   NO: '47',   NP: '977',
  NR: '674',  NU: '683',  NZ: '64',   OM: '968',  PA: '507',  PE: '51',
  PF: '689',  PG: '675',  PH: '63',   PK: '92',   PL: '48',   PM: '508',
  PN: '64',   PR: '1',    PS: '970',  PT: '351',  PW: '680',  PY: '595',
  QA: '974',  RE: '262',  RO: '40',   RS: '381',  RU: '7',    RW: '250',
  SA: '966',  SB: '677',  SC: '248',  SD: '249',  SE: '46',   SG: '65',
  SH: '290',  SI: '386',  SJ: '47',   SK: '421',  SL: '232',  SM: '378',
  SN: '221',  SO: '252',  SR: '597',  SS: '211',  ST: '239',  SV: '503',
  SX: '1',    SY: '963',  SZ: '268',  TC: '1',    TD: '235',  TF: '262',
  TG: '228',  TH: '66',   TJ: '992',  TK: '690',  TL: '670',  TM: '993',
  TN: '216',  TO: '676',  TR: '90',   TT: '1',    TV: '688',  TW: '886',
  TZ: '255',  UA: '380',  UG: '256',  UM: '1',    US: '1',    UY: '598',
  UZ: '998',  VA: '39',   VC: '1',    VE: '58',   VG: '1',    VI: '1',
  VN: '84',   VU: '678',  WF: '681',  WS: '685',  YE: '967',  YT: '262',
  ZA: '27',   ZM: '260',  ZW: '263'
};

